name: "first workflow"
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name : "Checking out code"
              uses : actions/checkout@v4
            
            - name : "Listing directories"
              run : ls -a 
            - name : "Writing  a file"
              run : echo "Errizuka">uday.txt
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name : "Printing Directoirs"
              run : ls -a 

