name: "Matrix - Running same job in different environemts"
on : 
    push:
        branches: ["main"]
jobs:
    job-1:
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest,windows-latest]
            images: [hello-world,alphine]
            exclude:
              - images : alphine
                os : windows-latest
            
        
        runs-on: ${{matrix.os}}
        steps:
            - name : "Printing docker info"
              run : docker info
            - name : "Ruuning a imgae on os ${{matrix.os}}"
              run : docker run ${{matrix.images}}
