name: "Variables"
on: push

jobs:
    job-1:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name : "Acessing secrests and Printing"
              run : echo ${{secrets.UDAY}}
            - name : "Printing varaiables"
              run : echo ${{vars.DOCKER_USERNAME}}
            - name : "Sleeping "
              run : sleep 6000s
